szakok = [
    {"nev": "Autógyártó ", "kod": "0062 ", "leiras": "Elektronika és elektrotechnika ágazat képzése, amely érettségivel és technikus szintű szakképzettség megszerzésével zárul. Az erősáramú elektrotechnikus az üzemi energetikai hálózatok létesítését, üzemeltetését, a villamosenergia-gazdálkodás nyomon követését, épületek energetikai, informatikai, vezérlési és jelátviteli hálózatának létesítését végző szakember. Feladatkörébe tartozik az alkalmazott irányítástechnikai, valamint hajtástechnikai installáció kezelése, összeállítása és üzemeltetése is. Nemcsak a hagyományos, de az okosotthonok telepítésében és programozásában is jártas, tisztában van a felhasználói programokkal, illetve azok alkalmazásával is, ismeri és alkalmazza a méréstechnikai elveket és eszközöket. A villanyszerelők tudásanyagát is ismerve együttműködik e szakterület munkatársaival. Ajánlott azon ﬁatalok számára, akik szeretik a számítástechnikát és az elektronikát, valamint érdeklődnek a villamos gépek, épületek, berendezések működése és irányítása iránt. A napjainkban dinamikusan terjedő okosmegoldások tekintetében is komoly szakmai jövőt, változatos feladatokat ígérő szakma. Szakirányú felsőfokú tanulmányok folytatására nyitott ﬁatalok számára is ajánlott.", "ido": "3 év"},
    {"nev": "Automatikai technikus", "kod": "0053", "leiras": "Elektronika és elektrotechnika ágazat képzése, amely érettségivel és technikus szintű szakképzettség megszerzésével zárul. Választható szakmairányok: Autóipar szakmairány, Energetika és petrolkémia szakmairány, Épületautomatizálás szakmairány, Gyártástechnika szakmairány. Az automatikai technikus az automatizált gépek, berendezések, rendszerek és épületek szerelését, üzembe helyezését, karbantartását végző szakember. A képzés során elsajátított pneumatikai és hidraulikai ismeretek birtokában alkalmas vezérlési és szabályozási feladatok ellátására is, emellett alapos PLC (programozható logikai vezérlő) ismeretekkel rendelkezik. Ajánlott azoknak a fiataloknak, akiket vonz a gépek, berendezések és épületek önműködő irányítása. A szakmát választók a XXI. század ígéretes szakembereivé válhatnak, akik kiemelkedő elhelyezkedési eséllyel indulnak a munkaerőpiacon. Remek választás azok számára is, akik nyitottak szakirányú felsőfokú tanulmányok folytatására.", "ido": " 5 év"},
    {"nev": "Elektronikai technikus", "kod": "0051", "leiras": "Elektronika és elektrotechnika ágazat képzése, amely érettségivel és technikus szintű szakképzettség megszerzésével zárul. Az elektronikai technikus a gyártó és a kiszolgáló ágazatok elektronikai és elektrotechnikai szakembere. Alapvető feladatai közé tartozik az elektromos, valamint elektronikus berendezések, műszerek tervezése, gyártása, összeszerelése, mérése, javítása és karbantartása. Együtt dolgozik a mérnökségi területekkel. Ismeri és alkalmazza a villamos biztonságtechnikai, illetőleg a korszerű ESD (elektrosztatikus kisülés elleni) védelmi előírásokat. Ajánlott mindazon fiatalok számára, akiket egyaránt vonz az elektronika és számítástechnika folyamatosan fejlődő világa. Javasolt továbbá azoknak, akik érdekelődnek az olyan gépek, berendezések működése, irányítása iránt, mint például az automatizált gyártósoroké és ipari robotoké. A képzést elvégzők keresett szakemberek a munkaerőpiacon, de találó választás a szakirányú felsőfokú tanulmányok folytatására nyitott ﬁatalok számára is.", "ido": "5 év "},
    {"nev": "Erősáramú elektrotechnikus", "kod": "0052", "leiras": "Elektronika és elektrotechnika ágazat képzése, amely érettségivel és technikus szintű szakképzettség megszerzésével zárul. Az erősáramú elektrotechnikus az üzemi energetikai hálózatok létesítését, üzemeltetését, a villamosenergia-gazdálkodás nyomon követését, épületek energetikai, informatikai, vezérlési és jelátviteli hálózatának létesítését végző szakember. Feladatkörébe tartozik az alkalmazott irányítástechnikai, valamint hajtástechnikai installáció kezelése, összeállítása és üzemeltetése is. Nemcsak a hagyományos, de az okosotthonok telepítésében és programozásában is jártas, tisztában van a felhasználói programokkal, illetve azok alkalmazásával is, ismeri és alkalmazza a méréstechnikai elveket és eszközöket. A villanyszerelők tudásanyagát is ismerve együttműködik e szakterület munkatársaival. Ajánlott azon ﬁatalok számára, akik szeretik a számítástechnikát és az elektronikát, valamint érdeklődnek a villamos gépek, épületek, berendezések működése és irányítása iránt. A napjainkban dinamikusan terjedő okosmegoldások tekintetében is komoly szakmai jövőt, változatos feladatokat ígérő szakma. Szakirányú felsőfokú tanulmányok folytatására nyitott ﬁatalok számára is ajánlott.", "ido": "5 év "},
    {"nev": "Finommechanikai műszerész", "kod": "0063", "leiras": "Gépészet ágazat képzése, amely szakképzettség megszerzésével zárul. A ﬁnommechanikai műszerész munkája során bonyolult kialakítású, kisméretű eszközöket készít, szerel, javít és karbantart. Ilyenek többek között a mérőműszerek, laboratóriumi, optikai és hajózási eszközök, vagy akár egyes hétköznapi használati tárgyak, mint például egy karóra. Alkatrészt gyárt, alakít, javít. Gépelemeket és gépszerkezeteket szerel, javít. Elvégzi a speciális ﬁnommechanikai elemek szerelését. Ajánlott minden fiatal számára, aki szeretne műszerek gyártásában, javításában részt venni.", "ido": "3 év "},{"nev": "Gépjármű-mechatronikai technikus", "kod": "0054", "leiras": "Specializált gép- és járműgyártás ágazat képzése, amely érettségivel és technikus szintű szakképzettség megszerzésével zárul. Választható szakmairányok: Gyártás, Motorkerékpár- és versenymotorszerelés, Szerviz. A Gépjármű-mechatronikai technikus munkája során a közúti járművek gyártásának, szervizelésének, illetve karbantartásának műszaki feltételeit biztosító tevékenységeket lát el. Ez magában foglalja a gépjárművek valamennyi gépészeti, villamos és elektronikus egységeire vonatkozó karbantartási, műszaki állapotvizsgálati, hibafeltárási, hibaelhárítási, beállítási és fenntartási műveleteit. Alternatív gépjármű hajtások (pl.: hibrid- vagy tiszta elektromos hajtás, LPG vagy CNG, stb.) Ajánlott minden fiatal számára, aki szereti a gépjárműveket és kíváncsi az előállításukra. Javasolt továbbá azoknak, akik szeretik a látványos eredményeket, valamint érdeklődnek az alternatív hajtású járművek iránt.", "ido": "5 év "},
    {"nev": "Közlekedésautomatikai technikus", "kod": "0057", "leiras": "Elektronika és elektrotechnika ágazat képzése, amely érettségivel és technikus szintű szakképzettség megszerzésével zárul. A közlekedésautomatikai technikus a kötöttpályás közlekedési rendszerek — vasút, metró — szakembere. Munkája ötvözi az elektrotechnikai, elektronikai, valamint az alapvető vasúti ismereteket. Alapvető feladatai közé tartozik a legfontosabb mechanikai és villamosáramköri ellenőrzések, mérések végrehajtása és a berendezések hibamegelőző karbantartása. Ismeri és munkája során alkalmazza az építési, üzemeltetési és karbantartási előírásokat, módszereket. Nemcsak a kötött pálya szerelmeseinek ajánlott, de remek választás mindazon fiatalok számára, akik érdeklődnek a vonatok biztonságos közlekedéséért felelős műszaki eszközök, intelligens közlekedésautomatikai rendszerek működése iránt. A képzés elvégzésével lehetőség nyílik szakirányú felsőfokú tanulmányok folytatására is.", "ido": "5 év"},
    {"nev": "Szoftverfejlesztő és -tesztelő", "kod": "0055", "leiras": "Informatika és távközlés ágazat képzése, amely érettségivel és technikus szintű szakképzettség megszerzésével zárul. A szoftverfejlesztő és -tesztelő technikus olyan szakember, aki képes webes és asztali alkalmazást (szoftvert) tervezni, fejleszteni, tesztelni és dokumentálni. A programozási feladatokon túl adatbázisok tervezését és kezelését is elvégzi. Csapatban dolgozva együttműködik a szoftverfejlesztési projektben résztvevő többi munkatársával, képes a csoportmunkát támogató fejlesztői eszközök hatékony használatára. Ajánlott minden ﬁatal számára, akit az informatikai szoftverek világa nemcsak vonz, hanem azok fejlesztése, tökéletesítése is érdekel.", "ido": "5 év"},
    {"nev": "Távközlési technikus", "kod": "0056", "leiras": "Informatika és távközlés ágazat képzése, amely érettségivel és technikusi szintű szakképzettség szakképzettség megszerzésével zárul. A távközlési technikus feladata különböző távközlési, elsősorban vezeték nélküli adatátviteli rendszerek telepítése és üzemeltetése. A technikus részt vesz a távközlési beruházásokban, a berendezések installálásában és a hálózat kiépítésében. Az általa telepített rendszerek biztosítják a mobiltelefonok és WiFi berendezések vezeték nélküli kapcsolatait. Biztosítanak földfelszíni és műholdas kép-, hang- és adatátvitelt, zárt infokommunikációs hálózatokban mikrohullámú átvitelt. Üzemelteti a rendszerben lévő eszközöket és berendezéseket, hibát kezel és javít. Ajánlott minden fiatal számára, akit a dinamikusan fejlődő távközlés modern világa a részletektől a hálózati szintig érdekel és vonz. Akit érdekel a vezeték nélküli technológia, szeretné tudni miképp jut el a kép, a hang és az adat az infokommunikációs eszközökre. Szeret csapatban dolgozni és szereti a kihívásokat.", "ido": "5 év"},
    {"nev": "Vasútforgalmi szolgálattevő technikus", "kod": "0058", "leiras": "Közlekedés és szállítmányozás ágazat képzése, amely érettségivel és technikus szintű szakképzettség megszerzésével zárul. A vasútforgalmi szolgálattevő technikus feladata a szakmai utasítások szerint hatáskörébe tartozó állomásokon és azok szolgálati helyein a menetrendszerű vonatközlekedés, és a tolatás biztonságos és hatékony megszervezése rendes üzemi körülmények között és rendkívüli helyzetekben egyaránt. Rendelkezéseit az állomáson és a nyíltvonalon valamennyi forgalmi tevékenységet ellátó dolgozó köteles tudomásul venni és végrehajtani. Ajánlott minden fiatal számára, akit érdekel a vasúti közlekedés és szeretne aktív részese lenni a vasúti közlekedés mindennapi szervezésének és irányításának.", "ido": "5 év "},
    {"nev": "Villanyszerelő", "kod": "0061", "leiras": "Elektronika és elektrotechnika ágazat képzése, amely szakképzettség megszerzésével zárul. Lehetséges szakmairányok: Épületvillamosság szakmairány, Villamoshálózat szakmairány, Villamos készülék és berendezésszerelő szakmairány. A villanyszerelő épületek, létesítmények és hálózatok hagyományos és intelligens villamos és napelemes rendszerének kialakítását végző szakember. Az ipari és kommunális létesítmények villamos berendezésének szerelése során kapcsoló- és elosztóberendezést telepít, ipari energiaelosztó vezetéket, szabadvezetéket, kábelt, vezérlő- és szabályozókészüléket, berendezést szerel, javít. Feladatkörébe tartozik a villamos ellenőrző mérések, vizsgálatok és beállítások elvégzése is. Ajánlott mindazon ﬁatalok számára, akiket nemcsak vonz a villamosság, de készek a felelős munkavégzésre egy olyan szakmában, amely napjainkra rendkívül felértékelődött. A szakma jó perspektívát és változatos feladatokat kínál.", "ido": "3 év"},
]

szakok.forEach(szak => {

    var div = document.createElement("div");

    div.classList.add("kartya");

    for (const valami in szak) {
        var valami2 = document.createElement("p");
        valami2.innerText = szak[valami];
        div.appendChild(valami2);
    }

    document.getElementById("szakok").appendChild(div);
});